### ISSUE TITLE
Can't install subcmd dependency library 

### ISSUE THREAD

**Issue by ironworld** [repejota/fhost#1]
Hi repejota!

First of all, congratulations for this idea!

I've got some problems when I tried to run the script. I can't install subcmd from pipy. Please, could you add these library to the repository?

Best Regards,

Cícero

**Comment by repejota** [comment]
Thank you!
I'm working on it ... just finishing docs for subcmd module ( another little project :) ) should be ready tonight but I want to be sure both projects are well documented.

If you want you can install subcmd directly from its repo: https://github.com/repejota/subcmd

Hope you find useful "fhost" I'm planning more features for it ... don't hesitate to ask and propose anything you need. :)

**Comment by ironworld** [comment]
Hi repejota!

Thanks a lot for your explanation. I will download the subcmd module (as you suggested) and I will test the fhost, ok?

So, I'm closing the issue :).

Thanks!
